// MTA GTFS-RT feed URLs — no API key required as of 2025
export const SUBWAY_FEEDS: Record<string, string> = {
  "1": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "2": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "3": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "4": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "5": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "6": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "7": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "S": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs",
  "A": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace",
  "C": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace",
  "E": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace",
  "B": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-bdfm",
  "D": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-bdfm",
  "F": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-bdfm",
  "M": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-bdfm",
  "G": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-g",
  "J": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-jz",
  "Z": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-jz",
  "L": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-l",
  "N": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-nqrw",
  "Q": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-nqrw",
  "R": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-nqrw",
  "W": "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-nqrw",
};

export const ALERTS_FEED = "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/camsys%2Fsubway-alerts";

export interface StopInfo {
  id: string;
  name: string;
  lines: string[];
}

export const SUBWAY_STOPS: Record<string, StopInfo> = {
  "van cortlandt park-242 st": { id: "101", name: "Van Cortlandt Park-242 St", lines: ["1"] },
  "238 st": { id: "103", name: "238 St", lines: ["1"] },
  "231 st": { id: "104", name: "231 St", lines: ["1"] },
  "marble hill-225 st": { id: "105", name: "Marble Hill-225 St", lines: ["1"] },
  "215 st": { id: "106", name: "215 St", lines: ["1"] },
  "207 st": { id: "107", name: "207 St", lines: ["1"] },
  "dyckman st": { id: "108", name: "Dyckman St", lines: ["1"] },
  "191 st": { id: "109", name: "191 St", lines: ["1"] },
  "181 st 1": { id: "110", name: "181 St", lines: ["1"] },
  "168 st 1": { id: "111", name: "168 St", lines: ["1", "A", "C"] },
  "157 st": { id: "112", name: "157 St", lines: ["1"] },
  "145 st 1": { id: "113", name: "145 St", lines: ["1"] },
  "137 st-city college": { id: "114", name: "137 St-City College", lines: ["1"] },
  "125 st 1": { id: "115", name: "125 St", lines: ["1"] },
  "116 st-columbia university": { id: "116", name: "116 St-Columbia University", lines: ["1"] },
  "cathedral pkwy-110 st 1": { id: "117", name: "Cathedral Pkwy-110 St", lines: ["1"] },
  "103 st 1": { id: "118", name: "103 St", lines: ["1"] },
  "96 st 1": { id: "119", name: "96 St", lines: ["1", "2", "3"] },
  "86 st 1": { id: "120", name: "86 St", lines: ["1"] },
  "79 st": { id: "121", name: "79 St", lines: ["1"] },
  "72 st 1": { id: "122", name: "72 St", lines: ["1", "2", "3"] },
  "66 st-lincoln center": { id: "123", name: "66 St-Lincoln Center", lines: ["1"] },
  "59 st-columbus circle": { id: "124", name: "59 St-Columbus Circle", lines: ["1", "A", "B", "C", "D"] },
  "50 st 1": { id: "125", name: "50 St", lines: ["1", "C", "E"] },
  "times sq-42 st": { id: "127", name: "Times Sq-42 St", lines: ["1", "2", "3", "7", "N", "Q", "R", "W", "A", "C", "E", "S"] },
  "34 st-penn station 1": { id: "128", name: "34 St-Penn Station", lines: ["1", "2", "3"] },
  "28 st 1": { id: "129", name: "28 St", lines: ["1"] },
  "23 st 1": { id: "130", name: "23 St", lines: ["1"] },
  "18 st": { id: "131", name: "18 St", lines: ["1"] },
  "14 st 1": { id: "132", name: "14 St", lines: ["1", "2", "3"] },
  "christopher st-sheridan sq": { id: "133", name: "Christopher St-Sheridan Sq", lines: ["1"] },
  "houston st": { id: "134", name: "Houston St", lines: ["1"] },
  "canal st 1": { id: "135", name: "Canal St", lines: ["1"] },
  "franklin st": { id: "136", name: "Franklin St", lines: ["1"] },
  "chambers st 1": { id: "137", name: "Chambers St", lines: ["1", "2", "3"] },
  "cortlandt st 1": { id: "138", name: "Cortlandt St", lines: ["1"] },
  "rector st 1": { id: "139", name: "Rector St", lines: ["1"] },
  "south ferry": { id: "142", name: "South Ferry", lines: ["1"] },
  "harlem-148 st": { id: "201", name: "Harlem-148 St", lines: ["3"] },
  "145 st 23": { id: "204", name: "145 St", lines: ["2", "3"] },
  "135 st 23": { id: "205", name: "135 St", lines: ["2", "3"] },
  "125 st 23": { id: "206", name: "125 St", lines: ["2", "3"] },
  "116 st 23": { id: "207", name: "116 St", lines: ["2", "3"] },
  "central park north-110 st": { id: "208", name: "Central Park North-110 St", lines: ["2", "3"] },
  "72 st 23": { id: "209", name: "72 St", lines: ["2", "3"] },
  "nevins st": { id: "229", name: "Nevins St", lines: ["2", "3", "4", "5"] },
  "bergen st": { id: "230", name: "Bergen St", lines: ["2", "3"] },
  "grand army plaza": { id: "231", name: "Grand Army Plaza", lines: ["2", "3"] },
  "eastern pkwy-brooklyn museum": { id: "232", name: "Eastern Pkwy-Brooklyn Museum", lines: ["2", "3"] },
  "crown heights-utica av": { id: "235", name: "Crown Heights-Utica Av", lines: ["3", "4"] },
  "sutter av-rutland rd": { id: "236", name: "Sutter Av-Rutland Rd", lines: ["3"] },
  "saratoga av": { id: "237", name: "Saratoga Av", lines: ["3"] },
  "rockaway av 3": { id: "238", name: "Rockaway Av", lines: ["3"] },
  "junius st": { id: "239", name: "Junius St", lines: ["3"] },
  "pennsylvania av": { id: "240", name: "Pennsylvania Av", lines: ["3"] },
  "new lots av": { id: "241", name: "New Lots Av", lines: ["3"] },
  "wakefield-241 st": { id: "201", name: "Wakefield-241 St", lines: ["2"] },
  "nereid av": { id: "202", name: "Nereid Av", lines: ["2"] },
  "233 st": { id: "203", name: "233 St", lines: ["2"] },
  "225 st": { id: "204", name: "225 St", lines: ["2"] },
  "gun hill rd 2": { id: "205", name: "Gun Hill Rd", lines: ["2"] },
  "burke av 2": { id: "206", name: "Burke Av", lines: ["2"] },
  "allerton av 2": { id: "207", name: "Allerton Av", lines: ["2"] },
  "pelham pkwy 2": { id: "208", name: "Pelham Pkwy", lines: ["2"] },
  "bronx park east": { id: "209", name: "Bronx Park East", lines: ["2"] },
  "e 180 st 2": { id: "210", name: "E 180 St", lines: ["2"] },
  "west farms sq": { id: "211", name: "West Farms Sq-E Tremont Av", lines: ["2"] },
  "freeman st 2": { id: "212", name: "Freeman St", lines: ["2"] },
  "simpson st 2": { id: "213", name: "Simpson St", lines: ["2"] },
  "intervale av 2": { id: "214", name: "Intervale Av", lines: ["2"] },
  "prospect av 2": { id: "215", name: "Prospect Av", lines: ["2"] },
  "jackson av 2": { id: "216", name: "Jackson Av", lines: ["2"] },
  "3 av-149 st 2": { id: "217", name: "3 Av-149 St", lines: ["2"] },
  "flatbush av-brooklyn college": { id: "251", name: "Flatbush Av-Brooklyn College", lines: ["2", "5"] },
  "newkirk av": { id: "252", name: "Newkirk Av", lines: ["2"] },
  "avenue h": { id: "253", name: "Avenue H", lines: ["2"] },
  "avenue j": { id: "254", name: "Avenue J", lines: ["2"] },
  "kings hwy 2": { id: "255", name: "Kings Hwy", lines: ["2"] },
  "avenue m": { id: "256", name: "Avenue M", lines: ["2"] },
  "avenue u 2": { id: "257", name: "Avenue U", lines: ["2"] },
  "neck rd 2": { id: "258", name: "Neck Rd", lines: ["2"] },
  "sheepshead bay 2": { id: "259", name: "Sheepshead Bay", lines: ["2"] },
  "brighton beach 2": { id: "260", name: "Brighton Beach", lines: ["2"] },
  "ocean pkwy 2": { id: "261", name: "Ocean Pkwy", lines: ["2"] },
  "woodlawn": { id: "401", name: "Woodlawn", lines: ["4"] },
  "mosholu pkwy": { id: "402", name: "Mosholu Pkwy", lines: ["4"] },
  "fordham rd 4": { id: "403", name: "Fordham Rd", lines: ["4"] },
  "kingsbridge rd 4": { id: "404", name: "Kingsbridge Rd", lines: ["4"] },
  "bedford park blvd-lehman college": { id: "405", name: "Bedford Park Blvd-Lehman College", lines: ["4"] },
  "161 st-yankee stadium": { id: "416", name: "161 St-Yankee Stadium", lines: ["4", "B", "D"] },
  "149 st-grand concourse": { id: "418", name: "149 St-Grand Concourse", lines: ["4", "5"] },
  "138 st-grand concourse": { id: "419", name: "138 St-Grand Concourse", lines: ["4", "5", "6"] },
  "125 st 45": { id: "420", name: "125 St", lines: ["4", "5", "6"] },
  "eastchester-dyre av": { id: "501", name: "Eastchester-Dyre Av", lines: ["5"] },
  "baychester av": { id: "502", name: "Baychester Av", lines: ["5"] },
  "gun hill rd 5": { id: "503", name: "Gun Hill Rd", lines: ["5"] },
  "burke av": { id: "504", name: "Burke Av", lines: ["5"] },
  "allerton av": { id: "505", name: "Allerton Av", lines: ["5"] },
  "pelham pkwy 5": { id: "506", name: "Pelham Pkwy", lines: ["5"] },
  "morris park": { id: "507", name: "Morris Park", lines: ["5"] },
  "e 180 st": { id: "508", name: "E 180 St", lines: ["5"] },
  "west farms sq-e tremont av": { id: "509", name: "West Farms Sq-E Tremont Av", lines: ["5"] },
  "freeman st": { id: "510", name: "Freeman St", lines: ["5"] },
  "simpson st": { id: "511", name: "Simpson St", lines: ["5"] },
  "intervale av": { id: "512", name: "Intervale Av", lines: ["5"] },
  "prospect av 5": { id: "513", name: "Prospect Av", lines: ["5"] },
  "jackson av": { id: "514", name: "Jackson Av", lines: ["5"] },
  "3 av-149 st": { id: "515", name: "3 Av-149 St", lines: ["5"] },
  "pelham bay park": { id: "601", name: "Pelham Bay Park", lines: ["6"] },
  "buhre av": { id: "602", name: "Buhre Av", lines: ["6"] },
  "middletown rd": { id: "603", name: "Middletown Rd", lines: ["6"] },
  "westchester sq-e tremont av": { id: "604", name: "Westchester Sq-E Tremont Av", lines: ["6"] },
  "zerega av": { id: "605", name: "Zerega Av", lines: ["6"] },
  "castle hill av": { id: "606", name: "Castle Hill Av", lines: ["6"] },
  "parkchester": { id: "607", name: "Parkchester", lines: ["6"] },
  "st lawrence av": { id: "608", name: "St Lawrence Av", lines: ["6"] },
  "morrison av-soundview": { id: "609", name: "Morrison Av-Soundview", lines: ["6"] },
  "elder av": { id: "610", name: "Elder Av", lines: ["6"] },
  "whitlock av": { id: "611", name: "Whitlock Av", lines: ["6"] },
  "hunts point av": { id: "612", name: "Hunts Point Av", lines: ["6"] },
  "longwood av": { id: "613", name: "Longwood Av", lines: ["6"] },
  "e 149 st": { id: "614", name: "E 149 St", lines: ["6"] },
  "e 143 st-st marys st": { id: "615", name: "E 143 St-St Mary\'s St", lines: ["6"] },
  "cypress av": { id: "616", name: "Cypress Av", lines: ["6"] },
  "brook av": { id: "617", name: "Brook Av", lines: ["6"] },
  "3 av 138 st": { id: "618", name: "3 Av-138 St", lines: ["6"] },
  "59 st 456": { id: "629", name: "59 St", lines: ["4", "5", "6"] },
  "68 st-hunter college": { id: "628", name: "68 St-Hunter College", lines: ["6"] },
  "77 st": { id: "627", name: "77 St", lines: ["6"] },
  "86 st 6": { id: "626", name: "86 St", lines: ["6"] },
  "96 st 6": { id: "625", name: "96 St", lines: ["6"] },
  "103 st 6": { id: "624", name: "103 St", lines: ["6"] },
  "110 st 6": { id: "623", name: "110 St", lines: ["6"] },
  "116 st 6": { id: "622", name: "116 St", lines: ["6"] },
  "125 st 6": { id: "621", name: "125 St", lines: ["6"] },
  "33 st 6": { id: "632", name: "33 St", lines: ["6"] },
  "28 st 6": { id: "633", name: "28 St", lines: ["6"] },
  "23 st 6": { id: "634", name: "23 St", lines: ["6"] },
  "14 st-union sq": { id: "635", name: "14 St-Union Sq", lines: ["4", "5", "6", "N", "Q", "R", "W", "L"] },
  "astor pl": { id: "636", name: "Astor Pl", lines: ["6"] },
  "bleecker st": { id: "637", name: "Bleecker St", lines: ["6"] },
  "spring st 6": { id: "638", name: "Spring St", lines: ["6"] },
  "canal st 6": { id: "639", name: "Canal St", lines: ["6"] },
  "brooklyn bridge-city hall": { id: "640", name: "Brooklyn Bridge-City Hall", lines: ["4", "5", "6"] },
  "fulton st": { id: "640", name: "Fulton St", lines: ["2", "3", "4", "5", "A", "C", "J", "Z"] },
  "wall st 45": { id: "418", name: "Wall St", lines: ["4", "5"] },
  "bowling green": { id: "419", name: "Bowling Green", lines: ["4", "5"] },
  "grand central-42 st": { id: "631", name: "Grand Central-42 St", lines: ["4", "5", "6", "7", "S"] },
  "flushing-main st": { id: "701", name: "Flushing-Main St", lines: ["7"] },
  "mets-willets point": { id: "702", name: "Mets-Willets Point", lines: ["7"] },
  "103 st-corona plaza": { id: "706", name: "103 St-Corona Plaza", lines: ["7"] },
  "111 st 7": { id: "707", name: "111 St", lines: ["7"] },
  "junction blvd": { id: "708", name: "Junction Blvd", lines: ["7"] },
  "90 st-elmhurst av": { id: "709", name: "90 St-Elmhurst Av", lines: ["7"] },
  "82 st-jackson hts": { id: "710", name: "82 St-Jackson Hts", lines: ["7"] },
  "74 st-broadway": { id: "711", name: "74 St-Broadway", lines: ["7", "E", "F", "M", "R"] },
  "69 st 7": { id: "712", name: "69 St", lines: ["7"] },
  "61 st-woodside": { id: "713", name: "61 St-Woodside", lines: ["7"] },
  "52 st 7": { id: "714", name: "52 St", lines: ["7"] },
  "46 st 7": { id: "715", name: "46 St", lines: ["7"] },
  "40 st 7": { id: "716", name: "40 St", lines: ["7"] },
  "33 st-rawson st": { id: "717", name: "33 St-Rawson St", lines: ["7"] },
  "queensboro plaza 7": { id: "718", name: "Queensboro Plaza", lines: ["7", "N", "W"] },
  "court sq 7": { id: "719", name: "Court Sq", lines: ["7", "E", "G", "M"] },
  "34 st-hudson yards": { id: "726", name: "34 St-Hudson Yards", lines: ["7"] },
  "inwood-207 st": { id: "A02", name: "Inwood-207 St", lines: ["A"] },
  "dyckman st a": { id: "A03", name: "Dyckman St", lines: ["A"] },
  "190 st": { id: "A04", name: "190 St", lines: ["A"] },
  "181 st a": { id: "A05", name: "181 St", lines: ["A"] },
  "175 st": { id: "A06", name: "175 St", lines: ["A"] },
  "168 st a": { id: "A07", name: "168 St", lines: ["A", "C"] },
  "145 st a": { id: "A09", name: "145 St", lines: ["A", "C"] },
  "135 st a": { id: "A10", name: "135 St", lines: ["B", "C"] },
  "125 st a": { id: "A11", name: "125 St", lines: ["A", "B", "C", "D"] },
  "116 st a": { id: "A12", name: "116 St", lines: ["B", "C"] },
  "cathedral pkwy-110 st a": { id: "A13", name: "Cathedral Pkwy-110 St", lines: ["B", "C"] },
  "103 st a": { id: "A14", name: "103 St", lines: ["B", "C"] },
  "96 st a": { id: "A15", name: "96 St", lines: ["B", "C"] },
  "86 st a": { id: "A16", name: "86 St", lines: ["B", "C"] },
  "81 st-museum of natural history": { id: "A17", name: "81 St-Museum of Natural History", lines: ["B", "C"] },
  "72 st a": { id: "A18", name: "72 St", lines: ["B", "C"] },
  "59 st-columbus circle a": { id: "A19", name: "59 St-Columbus Circle", lines: ["A", "B", "C", "D"] },
  "50 st a": { id: "A20", name: "50 St", lines: ["C", "E"] },
  "42 st-port authority": { id: "A21", name: "42 St-Port Authority Bus Terminal", lines: ["A", "C", "E"] },
  "34 st-penn station a": { id: "A25", name: "34 St-Penn Station", lines: ["A", "C", "E"] },
  "23 st a": { id: "A27", name: "23 St", lines: ["C", "E"] },
  "14 st a": { id: "A28", name: "14 St", lines: ["A", "C", "E"] },
  "w 4 st-wash sq": { id: "A32", name: "W 4 St-Wash Sq", lines: ["A", "B", "C", "D", "E", "F", "M"] },
  "spring st a": { id: "A33", name: "Spring St", lines: ["C", "E"] },
  "canal st a": { id: "A34", name: "Canal St", lines: ["A", "C", "E"] },
  "chambers st a": { id: "A36", name: "Chambers St", lines: ["A", "C"] },
  "world trade center": { id: "E01", name: "World Trade Center", lines: ["E"] },
  "park pl": { id: "A38", name: "Park Pl", lines: ["A", "C"] },
  "fulton st a": { id: "A40", name: "Fulton St", lines: ["A", "C"] },
  "jay st-metrotech": { id: "A41", name: "Jay St-MetroTech", lines: ["A", "C", "F", "R"] },
  "hoyt-schermerhorn sts": { id: "A42", name: "Hoyt-Schermerhorn Sts", lines: ["A", "C", "G"] },
  "bergen st a": { id: "A43", name: "Bergen St", lines: ["A", "C"] },
  "euclid av": { id: "A44", name: "Euclid Av", lines: ["A", "C"] },
  "lefferts blvd": { id: "A45", name: "Lefferts Blvd", lines: ["A"] },
  "ozone park-lefferts blvd": { id: "A45", name: "Ozone Park-Lefferts Blvd", lines: ["A"] },
  "rockaway blvd": { id: "A46", name: "Rockaway Blvd", lines: ["A"] },
  "104 st": { id: "A47", name: "104 St", lines: ["A"] },
  "111 st a": { id: "A48", name: "111 St", lines: ["A"] },
  "aqueduct-n conduit av": { id: "A49", name: "Aqueduct-N Conduit Av", lines: ["A"] },
  "aqueduct racetrack": { id: "A50", name: "Aqueduct Racetrack", lines: ["A"] },
  "howard beach-jfk airport": { id: "A55", name: "Howard Beach-JFK Airport", lines: ["A"] },
  "broad channel": { id: "H02", name: "Broad Channel", lines: ["A"] },
  "far rockaway-mott av": { id: "H01", name: "Far Rockaway-Mott Av", lines: ["A"] },
  "beach 90 st": { id: "H03", name: "Beach 90 St", lines: ["A"] },
  "beach 98 st": { id: "H04", name: "Beach 98 St", lines: ["A"] },
  "beach 105 st": { id: "H05", name: "Beach 105 St", lines: ["A"] },
  "rockaway park-beach 116 st": { id: "H11", name: "Rockaway Park-Beach 116 St", lines: ["A"] },
  "woodhaven blvd a": { id: "A53", name: "Woodhaven Blvd", lines: ["A"] },
  "norwood-205 st": { id: "D01", name: "Norwood-205 St", lines: ["D"] },
  "bedford park blvd d": { id: "D03", name: "Bedford Park Blvd", lines: ["B", "D"] },
  "kingsbridge rd d": { id: "D04", name: "Kingsbridge Rd", lines: ["B", "D"] },
  "fordham rd d": { id: "D05", name: "Fordham Rd", lines: ["B", "D"] },
  "182-183 sts": { id: "D06", name: "182-183 Sts", lines: ["B", "D"] },
  "tremont av": { id: "D07", name: "Tremont Av", lines: ["B", "D"] },
  "174 st d": { id: "D08", name: "174 St", lines: ["B", "D"] },
  "grand concourse d": { id: "D09", name: "Grand Concourse", lines: ["B", "D"] },
  "161 st-yankee stadium d": { id: "D10", name: "161 St-Yankee Stadium", lines: ["B", "D"] },
  "155 st": { id: "D11", name: "155 St", lines: ["B", "D"] },
  "145 st d": { id: "D12", name: "145 St", lines: ["B", "D"] },
  "135 st d": { id: "D13", name: "135 St", lines: ["B", "D"] },
  "125 st d": { id: "D14", name: "125 St", lines: ["B", "D"] },
  "116 st d": { id: "D15", name: "116 St", lines: ["B", "D"] },
  "cathedral pkwy d": { id: "D16", name: "Cathedral Pkwy-110 St", lines: ["B", "D"] },
  "34 st-herald sq": { id: "D17", name: "34 St-Herald Sq", lines: ["B", "D", "F", "M", "N", "Q", "R", "W"] },
  "23 st d": { id: "D18", name: "23 St", lines: ["F", "M"] },
  "14 st d": { id: "D19", name: "14 St", lines: ["F", "M"] },
  "2 av": { id: "D20", name: "2 Av", lines: ["F"] },
  "delancey st-essex st": { id: "D21", name: "Delancey St-Essex St", lines: ["F", "J", "M", "Z"] },
  "broadway-lafayette st": { id: "D22", name: "Broadway-Lafayette St", lines: ["B", "D", "F", "M"] },
  "grand st d": { id: "D23", name: "Grand St", lines: ["B", "D"] },
  "atlantic av-barclays ctr": { id: "D24", name: "Atlantic Av-Barclays Ctr", lines: ["B", "D", "N", "Q", "R", "2", "3", "4", "5"] },
  "7 av d": { id: "D25", name: "7 Av", lines: ["B", "D", "E"] },
  "prospect park": { id: "D26", name: "Prospect Park", lines: ["B", "Q"] },
  "church av d": { id: "D27", name: "Church Av", lines: ["B", "Q"] },
  "avenue h d": { id: "D28", name: "Avenue H", lines: ["Q"] },
  "avenue j d": { id: "D29", name: "Avenue J", lines: ["Q"] },
  "avenue m d": { id: "D30", name: "Avenue M", lines: ["Q"] },
  "kings hwy q": { id: "D31", name: "Kings Hwy", lines: ["Q"] },
  "avenue u d": { id: "D32", name: "Avenue U", lines: ["Q"] },
  "neck rd d": { id: "D33", name: "Neck Rd", lines: ["Q"] },
  "sheepshead bay d": { id: "D34", name: "Sheepshead Bay", lines: ["Q"] },
  "brighton beach": { id: "D35", name: "Brighton Beach", lines: ["B", "Q"] },
  "ocean pkwy": { id: "D37", name: "Ocean Pkwy", lines: ["B", "Q"] },
  "coney island-stillwell av": { id: "D40", name: "Coney Island-Stillwell Av", lines: ["D", "F", "N", "Q"] },
  "bay pkwy d": { id: "D38", name: "Bay Pkwy", lines: ["D"] },
  "25 av": { id: "D39", name: "25 Av", lines: ["D"] },
  "9 av d": { id: "D41", name: "9 Av", lines: ["D"] },
  "fort hamilton pkwy d": { id: "D42", name: "Fort Hamilton Pkwy", lines: ["D"] },
  "50 st d": { id: "D43", name: "50 St", lines: ["D"] },
  "55 st": { id: "D44", name: "55 St", lines: ["D"] },
  "62 st": { id: "D45", name: "62 St", lines: ["D"] },
  "71 st": { id: "D46", name: "71 St", lines: ["D"] },
  "79 st d": { id: "D47", name: "79 St", lines: ["D"] },
  "18 av d": { id: "D48", name: "18 Av", lines: ["D"] },
  "20 av": { id: "D49", name: "20 Av", lines: ["D"] },
  "bay 50 st": { id: "D50", name: "Bay 50 St", lines: ["D"] },
  "jamaica-179 st": { id: "F01", name: "Jamaica-179 St", lines: ["F"] },
  "169 st": { id: "F02", name: "169 St", lines: ["F"] },
  "parsons blvd": { id: "F03", name: "Parsons Blvd", lines: ["F"] },
  "sutphin blvd": { id: "F04", name: "Sutphin Blvd", lines: ["F", "E", "J", "Z"] },
  "briarwood": { id: "F05", name: "Briarwood", lines: ["F", "E"] },
  "kew gardens-union tpke": { id: "F06", name: "Kew Gardens-Union Tpke", lines: ["F", "E"] },
  "75 av f": { id: "F07", name: "75 Av", lines: ["F", "E"] },
  "forest hills-71 av": { id: "F08", name: "Forest Hills-71 Av", lines: ["E", "F", "M", "R"] },
  "67 av": { id: "F09", name: "67 Av", lines: ["M", "R"] },
  "63 dr-rego center": { id: "F10", name: "63 Dr-Rego Center", lines: ["M", "R"] },
  "woodhaven blvd f": { id: "F11", name: "Woodhaven Blvd", lines: ["M", "R"] },
  "grand av-newtown": { id: "F12", name: "Grand Av-Newtown", lines: ["M"] },
  "elmhurst av": { id: "F13", name: "Elmhurst Av", lines: ["M", "R"] },
  "jackson hts-roosevelt av": { id: "F14", name: "Jackson Hts-Roosevelt Av", lines: ["E", "F", "M", "R"] },
  "65 st": { id: "F15", name: "65 St", lines: ["M", "R"] },
  "northern blvd": { id: "F16", name: "Northern Blvd", lines: ["M", "R"] },
  "46 st f": { id: "F17", name: "46 St", lines: ["M", "R"] },
  "steinway st": { id: "F18", name: "Steinway St", lines: ["M", "R"] },
  "36 st f": { id: "F19", name: "36 St", lines: ["M", "R"] },
  "queens plaza": { id: "F20", name: "Queens Plaza", lines: ["E", "M", "R"] },
  "21 st-queensbridge": { id: "F21", name: "21 St-Queensbridge", lines: ["F"] },
  "queensboro plaza f": { id: "F22", name: "Queensboro Plaza", lines: ["N", "W", "7"] },
  "ditmas av": { id: "F25", name: "Ditmas Av", lines: ["F"] },
  "18 av f": { id: "F26", name: "18 Av", lines: ["F"] },
  "avenue i": { id: "F27", name: "Avenue I", lines: ["F"] },
  "bay pkwy f": { id: "F28", name: "Bay Pkwy", lines: ["F"] },
  "avenue n": { id: "F29", name: "Avenue N", lines: ["F"] },
  "avenue p": { id: "F30", name: "Avenue P", lines: ["F"] },
  "kings hwy f": { id: "F31", name: "Kings Hwy", lines: ["F"] },
  "avenue u f": { id: "F32", name: "Avenue U", lines: ["F"] },
  "avenue x": { id: "F33", name: "Avenue X", lines: ["F"] },
  "neptune av": { id: "F34", name: "Neptune Av", lines: ["F"] },
  "church av g": { id: "G35", name: "Church Av", lines: ["F", "G"] },
  "court sq g": { id: "G22", name: "Court Sq", lines: ["G", "E", "M", "7"] },
  "21 st g": { id: "G24", name: "21 St", lines: ["G"] },
  "greenpoint av": { id: "G25", name: "Greenpoint Av", lines: ["G"] },
  "nassau av": { id: "G26", name: "Nassau Av", lines: ["G"] },
  "metropolitan av g": { id: "G27", name: "Metropolitan Av", lines: ["G"] },
  "broadway g": { id: "G28", name: "Broadway", lines: ["G"] },
  "flushing av g": { id: "G29", name: "Flushing Av", lines: ["G"] },
  "myrtle-willoughby avs": { id: "G30", name: "Myrtle-Willoughby Avs", lines: ["G"] },
  "bedford-nostrand avs": { id: "G31", name: "Bedford-Nostrand Avs", lines: ["G"] },
  "classon av": { id: "G32", name: "Classon Av", lines: ["G"] },
  "clinton-washington avs g": { id: "G33", name: "Clinton-Washington Avs", lines: ["G"] },
  "fulton st g": { id: "G34", name: "Fulton St", lines: ["G"] },
  "fort hamilton pkwy g": { id: "G35", name: "Fort Hamilton Pkwy", lines: ["G"] },
  "smith-9 sts": { id: "G36", name: "Smith-9 Sts", lines: ["F", "G"] },
  "4 av-9 st": { id: "G37", name: "4 Av-9 St", lines: ["F", "G", "R"] },
  "jamaica center-parsons-archer": { id: "J12", name: "Jamaica Center-Parsons/Archer", lines: ["E", "J", "Z"] },
  "sutphin blvd-archer av-jfk": { id: "J13", name: "Sutphin Blvd-Archer Av-JFK Airport", lines: ["E", "J", "Z"] },
  "jamaica-van wyck": { id: "J14", name: "Jamaica-Van Wyck", lines: ["E"] },
  "myrtle av j": { id: "J19", name: "Myrtle Av", lines: ["J", "M", "Z"] },
  "kosciuszko st": { id: "J20", name: "Kosciuszko St", lines: ["J", "M"] },
  "gates av j": { id: "J21", name: "Gates Av", lines: ["J", "M"] },
  "halsey st j": { id: "J22", name: "Halsey St", lines: ["J"] },
  "broadway j": { id: "J23", name: "Broadway", lines: ["J", "Z"] },
  "chauncey st": { id: "J24", name: "Chauncey St", lines: ["J", "Z"] },
  "alabama av": { id: "J25", name: "Alabama Av", lines: ["J"] },
  "van siclen av j": { id: "J26", name: "Van Siclen Av", lines: ["J", "Z"] },
  "cleveland st": { id: "J27", name: "Cleveland St", lines: ["J"] },
  "norwood av j": { id: "J28", name: "Norwood Av", lines: ["J"] },
  "crescent st": { id: "J29", name: "Crescent St", lines: ["J", "Z"] },
  "cypress hills j": { id: "J30", name: "Cypress Hills", lines: ["J"] },
  "75 st-elderts lane": { id: "J31", name: "75 St-Elderts Lane", lines: ["J"] },
  "woodhaven blvd j": { id: "J32", name: "Woodhaven Blvd", lines: ["J"] },
  "111 st j": { id: "J33", name: "111 St", lines: ["J"] },
  "121 st j": { id: "J34", name: "121 St", lines: ["J"] },
  "essex st": { id: "M18", name: "Essex St", lines: ["J", "M", "Z"] },
  "8 av l": { id: "L01", name: "8 Av", lines: ["L"] },
  "6 av l": { id: "L02", name: "6 Av", lines: ["L"] },
  "14 st-union sq l": { id: "L03", name: "14 St-Union Sq", lines: ["L"] },
  "3 av l": { id: "L04", name: "3 Av", lines: ["L"] },
  "1 av": { id: "L05", name: "1 Av", lines: ["L"] },
  "bedford av": { id: "L06", name: "Bedford Av", lines: ["L"] },
  "lorimer st": { id: "L07", name: "Lorimer St", lines: ["L"] },
  "graham av": { id: "L08", name: "Graham Av", lines: ["L"] },
  "grand st l": { id: "L09", name: "Grand St", lines: ["L"] },
  "montrose av": { id: "L10", name: "Montrose Av", lines: ["L"] },
  "morgan av": { id: "L11", name: "Morgan Av", lines: ["L"] },
  "jefferson st l": { id: "L12", name: "Jefferson St", lines: ["L"] },
  "dekalb av l": { id: "L13", name: "DeKalb Av", lines: ["L"] },
  "myrtle-wyckoff avs": { id: "L14", name: "Myrtle-Wyckoff Avs", lines: ["L", "M"] },
  "halsey st l": { id: "L15", name: "Halsey St", lines: ["L"] },
  "wilson av": { id: "L16", name: "Wilson Av", lines: ["L"] },
  "bushwick av-aberdeen st": { id: "L17", name: "Bushwick Av-Aberdeen St", lines: ["L"] },
  "broadway junction": { id: "L18", name: "Broadway Junction", lines: ["A", "C", "J", "L", "Z"] },
  "atlantic av l": { id: "L19", name: "Atlantic Av", lines: ["L"] },
  "east new york": { id: "L20", name: "East New York", lines: ["L"] },
  "sutter av l": { id: "L21", name: "Sutter Av", lines: ["L"] },
  "livonia av": { id: "L22", name: "Livonia Av", lines: ["L"] },
  "new lots av l": { id: "L23", name: "New Lots Av", lines: ["L"] },
  "e 105 st": { id: "L24", name: "E 105 St", lines: ["L"] },
  "canarsie-rockaway pkwy": { id: "L29", name: "Canarsie-Rockaway Pkwy", lines: ["L"] },
  "astoria-ditmars blvd": { id: "R01", name: "Astoria-Ditmars Blvd", lines: ["N", "W"] },
  "astoria blvd": { id: "R02", name: "Astoria Blvd", lines: ["N", "W"] },
  "30 av": { id: "R03", name: "30 Av", lines: ["N", "W"] },
  "broadway astoria": { id: "R04", name: "Broadway", lines: ["N", "W"] },
  "36 av": { id: "R05", name: "36 Av", lines: ["N", "W"] },
  "39 av-dutch kills": { id: "R06", name: "39 Av-Dutch Kills", lines: ["N", "W"] },
  "36 st queens": { id: "R08", name: "36 St", lines: ["N", "W"] },
  "queensboro plaza": { id: "R09", name: "Queensboro Plaza", lines: ["N", "W", "7"] },
  "lexington av-59 st": { id: "R11", name: "Lexington Av-59 St", lines: ["N", "Q", "R", "W", "4", "5", "6"] },
  "5 av-59 st": { id: "R13", name: "5 Av-59 St", lines: ["N", "R", "W"] },
  "57 st-7 av": { id: "R14", name: "57 St-7 Av", lines: ["N", "Q", "R", "W"] },
  "49 st": { id: "R15", name: "49 St", lines: ["N", "Q", "R", "W"] },
  "42 st-bryant pk": { id: "R16", name: "42 St-Bryant Pk", lines: ["B", "D", "F", "M"] },
  "34 st-herald sq r": { id: "R17", name: "34 St-Herald Sq", lines: ["N", "Q", "R", "W"] },
  "28 st r": { id: "R20", name: "28 St", lines: ["N", "R", "W"] },
  "23 st r": { id: "R21", name: "23 St", lines: ["N", "R", "W"] },
  "city hall r": { id: "R22", name: "City Hall", lines: ["N", "Q", "R", "W"] },
  "canal st r": { id: "R23", name: "Canal St", lines: ["N", "Q", "R", "W"] },
  "prince st": { id: "R24", name: "Prince St", lines: ["N", "Q", "R", "W"] },
  "8 st-nyu": { id: "R25", name: "8 St-NYU", lines: ["N", "Q", "R", "W"] },
  "cortlandt st r": { id: "R28", name: "Cortlandt St", lines: ["N", "Q", "R", "W"] },
  "rector st r": { id: "R29", name: "Rector St", lines: ["N", "R", "W"] },
  "whitehall st-south ferry": { id: "R30", name: "Whitehall St-South Ferry", lines: ["N", "R", "W"] },
  "court st": { id: "R31", name: "Court St", lines: ["R"] },
  "jay st-metrotech r": { id: "R31", name: "Jay St-MetroTech", lines: ["R"] },
  "union st": { id: "R32", name: "Union St", lines: ["R"] },
  "4 av-9 st r": { id: "R33", name: "4 Av-9 St", lines: ["R"] },
  "prospect av r": { id: "R34", name: "Prospect Av", lines: ["R"] },
  "25 st r": { id: "R35", name: "25 St", lines: ["R"] },
  "36 st r": { id: "R36", name: "36 St", lines: ["R", "D", "N"] },
  "45 st": { id: "R37", name: "45 St", lines: ["R"] },
  "53 st r": { id: "R38", name: "53 St", lines: ["R"] },
  "59 st r": { id: "R39", name: "59 St", lines: ["R", "D", "N"] },
  "bay ridge av": { id: "R40", name: "Bay Ridge Av", lines: ["R"] },
  "77 st r": { id: "R41", name: "77 St", lines: ["R"] },
  "86 st r": { id: "R42", name: "86 St", lines: ["R"] },
  "95 st r": { id: "R43", name: "95 St", lines: ["R"] },
  "bay ridge-95 st": { id: "R43", name: "Bay Ridge-95 St", lines: ["R"] },
  "96 st q": { id: "Q01", name: "96 St", lines: ["Q"] },
  "86 st q": { id: "Q02", name: "86 St", lines: ["Q"] },
  "72 st q": { id: "Q03", name: "72 St", lines: ["Q"] },
  "57 st q": { id: "Q04", name: "57 St", lines: ["Q", "N"] },
  "times sq s": { id: "S01", name: "Times Sq", lines: ["S"] },
  "grand central s": { id: "S03", name: "Grand Central", lines: ["S"] },
  "franklin av s": { id: "S04", name: "Franklin Av", lines: ["S", "C"] },
  "prospect park s": { id: "S05", name: "Prospect Park", lines: ["S"] },
  "botanic garden": { id: "S06", name: "Botanic Garden", lines: ["S"] },
  "rockaway park s": { id: "S07", name: "Rockaway Park-Beach 116 St", lines: ["S"] },
  "broad channel s": { id: "S08", name: "Broad Channel", lines: ["S"] },
  "aqueduct s": { id: "S09", name: "Aqueduct-N Conduit Av", lines: ["S"] },
};

export function findStopId(stationName: string): string | null {
  const normalized = stationName.toLowerCase().trim()
    .replace(/\bstreet\b/g, "st").replace(/\bavenue\b/g, "av")
    .replace(/\bboulevard\b/g, "blvd").replace(/[-–]/g, " ")
    .replace(/\s+/g, " ");

  if (SUBWAY_STOPS[normalized]) return SUBWAY_STOPS[normalized].id;

  let bestMatch: string | null = null;
  let bestScore = 0;

  for (const [key, val] of Object.entries(SUBWAY_STOPS)) {
    let score = 0;
    if (key === normalized) score = 100;
    else if (key.startsWith(normalized)) score = 80;
    else if (normalized.startsWith(key)) score = 75;
    else if (key.includes(normalized)) score = 60;
    else if (normalized.includes(key)) score = 55;
    else {
      const keyWords = key.split(" ");
      const normWords = normalized.split(" ");
      const matches = normWords.filter(w => w.length > 2 && keyWords.includes(w)).length;
      if (matches > 0) score = matches * 20;
    }
    if (score > bestScore) {
      bestScore = score;
      bestMatch = val.id;
    }
  }

  return bestScore >= 20 ? bestMatch : null;
}

export function getFeedUrl(line: string): string {
  return SUBWAY_FEEDS[line.toUpperCase()] || SUBWAY_FEEDS["1"];
}